#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 学籍管理系统_02
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StudentManagement")]
	public partial class ScoreClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertScore(Score instance);
    partial void UpdateScore(Score instance);
    partial void DeleteScore(Score instance);
    #endregion
		
		public ScoreClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StudentManagementConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ScoreClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScoreClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScoreClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScoreClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Score> Score
		{
			get
			{
				return this.GetTable<Score>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Score")]
	public partial class Score : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Student_Number;
		
		private string _Student_Name;
		
		private string _Student_Class;
		
		private System.Nullable<int> _Chinese;
		
		private System.Nullable<int> _Math;
		
		private System.Nullable<int> _English;
		
		private System.Nullable<int> _Physical;
		
		private System.Nullable<int> _chemistry;
		
		private System.Nullable<int> _organisms;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_NumberChanging(string value);
    partial void OnStudent_NumberChanged();
    partial void OnStudent_NameChanging(string value);
    partial void OnStudent_NameChanged();
    partial void OnStudent_ClassChanging(string value);
    partial void OnStudent_ClassChanged();
    partial void OnChineseChanging(System.Nullable<int> value);
    partial void OnChineseChanged();
    partial void OnMathChanging(System.Nullable<int> value);
    partial void OnMathChanged();
    partial void OnEnglishChanging(System.Nullable<int> value);
    partial void OnEnglishChanged();
    partial void OnPhysicalChanging(System.Nullable<int> value);
    partial void OnPhysicalChanged();
    partial void OnchemistryChanging(System.Nullable<int> value);
    partial void OnchemistryChanged();
    partial void OnorganismsChanging(System.Nullable<int> value);
    partial void OnorganismsChanged();
    #endregion
		
		public Score()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this.OnStudent_NumberChanging(value);
					this.SendPropertyChanging();
					this._Student_Number = value;
					this.SendPropertyChanged("Student_Number");
					this.OnStudent_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this.OnStudent_NameChanging(value);
					this.SendPropertyChanging();
					this._Student_Name = value;
					this.SendPropertyChanged("Student_Name");
					this.OnStudent_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Class", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_Class
		{
			get
			{
				return this._Student_Class;
			}
			set
			{
				if ((this._Student_Class != value))
				{
					this.OnStudent_ClassChanging(value);
					this.SendPropertyChanging();
					this._Student_Class = value;
					this.SendPropertyChanged("Student_Class");
					this.OnStudent_ClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chinese", DbType="Int")]
		public System.Nullable<int> Chinese
		{
			get
			{
				return this._Chinese;
			}
			set
			{
				if ((this._Chinese != value))
				{
					this.OnChineseChanging(value);
					this.SendPropertyChanging();
					this._Chinese = value;
					this.SendPropertyChanged("Chinese");
					this.OnChineseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math", DbType="Int")]
		public System.Nullable<int> Math
		{
			get
			{
				return this._Math;
			}
			set
			{
				if ((this._Math != value))
				{
					this.OnMathChanging(value);
					this.SendPropertyChanging();
					this._Math = value;
					this.SendPropertyChanged("Math");
					this.OnMathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English", DbType="Int")]
		public System.Nullable<int> English
		{
			get
			{
				return this._English;
			}
			set
			{
				if ((this._English != value))
				{
					this.OnEnglishChanging(value);
					this.SendPropertyChanging();
					this._English = value;
					this.SendPropertyChanged("English");
					this.OnEnglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physical", DbType="Int")]
		public System.Nullable<int> Physical
		{
			get
			{
				return this._Physical;
			}
			set
			{
				if ((this._Physical != value))
				{
					this.OnPhysicalChanging(value);
					this.SendPropertyChanging();
					this._Physical = value;
					this.SendPropertyChanged("Physical");
					this.OnPhysicalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chemistry", DbType="Int")]
		public System.Nullable<int> chemistry
		{
			get
			{
				return this._chemistry;
			}
			set
			{
				if ((this._chemistry != value))
				{
					this.OnchemistryChanging(value);
					this.SendPropertyChanging();
					this._chemistry = value;
					this.SendPropertyChanged("chemistry");
					this.OnchemistryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organisms", DbType="Int")]
		public System.Nullable<int> organisms
		{
			get
			{
				return this._organisms;
			}
			set
			{
				if ((this._organisms != value))
				{
					this.OnorganismsChanging(value);
					this.SendPropertyChanging();
					this._organisms = value;
					this.SendPropertyChanged("organisms");
					this.OnorganismsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
